HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>error</title>
</head>
<body>
	<center>
		<h1>Lo sentimos, el servicio no se encuentra disponible</h1><br>
		<img src="https://cdn-icons-png.flaticon.com/512/1886/1886495.png" width="40%"><br>
		<h2> Disculpe las molestias, intente mas tarde </h2>
	</center>
</body>
</html>